In [7]:
#Loading the Necessary Packages
import pandas as pd
import numpy as np

# Step 1: Loading the dataset
df = pd.read_csv("data.csv")

# This line finds any missing values in the 'Calories' column and fills them with the average of that column, ensuring our math works perfectly later.
df['Calories'] = df['Calories'].fillna(df['Calories'].mean())

#This Prints a Message that shows that All the Necssary Libraries are being Submitted
print("Libraries imported and data loaded successfully!")

Libraries imported and data loaded successfully!


In [8]:
#Step 2: Creation of the 1D Arrays
# Create a 1D NumPy array taking the first 12 values from the Calories column
calories_1d = np.array(df['Calories'].head(12))


# df['Calories'].head(12) grabs exactly the first 12 numbers from the Calories column.
# np.array(...) takes those 12 numbers and officially turns them into a NumPy 1D array.
# We save this new array inside a variable named 'calories_1d'

#Step 3:  Performing  math operations
mean_cal = np.mean(calories_1d) # np.mean() adds all 12 numbers together and divides by 12 to find the exact mathematical average.

std_cal = np.std(calories_1d) # np.std() calculates the Standard Deviation

print("--- 1D Array (Calories) ---") # These lines print out our results.
print(calories_1d) # Shows you the actual list of 12 numbers

# The {:.2f} is a neat formatting trick. It tells Python: "Only show 2 decimal places," so we get 78.05 instead of 78.0548765...
print(f"\nMean (Average): {mean_cal:.2f}")
print(f"Standard Deviation (Variance): {std_cal:.2f}")

--- 1D Array (Calories) ---
[409.1 479.  340.  282.4 406.  300.  374.  253.3 195.1 269.  329.3 250.7]

Mean (Average): 323.99
Standard Deviation (Variance): 78.05


In [9]:
# Step 4: Creation of 2D Arrays/ Reshaping of the 2D Arrays too
# Reshape the 12-item 1D array into a 3x4 2D array
array_2d = calories_1d.reshape(3, 4) # .reshape(3, 4) takes our flat list of 12 numbers and organizes them into 3 rows and 4 columns (since 3 x 4 = 12).
# We save this new grid into a variable called 'array_2d'

print("--- 2D Array (Reshaped to 3 rows, 4 columns) ---")
print(array_2d) # Prints the numbers in their new grid format

# Let's check the new "shape" to confirm
print(f"\nThe shape of this array is now: {array_2d.shape}") # .shape is a quick command to check the dimensions of an array. It will print out "(3, 4)" proving we successfully made 3 rows and 4 columns.

--- 2D Array (Reshaped to 3 rows, 4 columns) ---
[[409.1 479.  340.  282.4]
 [406.  300.  374.  253.3]
 [195.1 269.  329.3 250.7]]

The shape of this array is now: (3, 4)


Step 6: Explanation of Each Array Operations
Array Explanations & Operations:

1. 1D Array: I extracted a subset of the Calories data into a 1-Dimensional NumPy array.

- Using this array, I calculated the Mean (the average calories burned) and the Standard Deviation (how much the calorie burn varies from that average).

2. 2D Array & Reshaping: I took the flat 1D array of 12 elements and used the .reshape() function to convert it into a 2-Dimensional array (a matrix with 3 rows and 4 columns).

- ]
Understanding how to reshape arrays is a crucial part of vectorization and preparing data for machine learning models, as models often require data in specific multi-dimensional formats.

